### ISSUE TITLE
How to handle two factor authentication?

### ISSUE THREAD

**Issue by ChayoteJarocho** [a-gubskiy/X.Bluesky#21]
I don't see this in the readme or in the source code: How can I handle the basic two factor authentication that Bluesky offers? (require email code):

![image](https://github.com/user-attachments/assets/b1f835de-cd12-47f8-9986-71bcecfe6844)

If I enable this setting, I get this error when attempting to login with my username and password:
```
Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by a-gubskiy** [comment]
Hmm... I didn't handle this case. I need to investigate it!

**Comment by drasticactions** [comment]
For third-party clients, you should use [app passwords](https://atproto.com/ja/specs/xrpc). I believe the email codes are for main account passwords, which you should avoid using outside of the main Bsky app.

AFAIK for these use cases, Oauth would be the preferred path going forward.

**Comment by xforever1313** [comment]
I can confirm that app passwords work perfectly with this library!  My bots use app passwords and can authenticate successfully.

**Comment by a-gubskiy** [comment]
So currently the app passwords is affordable solution.
